#!/usr/bin/env bash
# scripts/build-extensions.sh
# Generates two extension builds under dist/:
#   dist/extension-prod/  — production, locked to https://www.caliber-app.com
#   dist/extension-dev/   — development, locked to http://localhost:3000
#
# Usage:  bash scripts/build-extensions.sh

set -euo pipefail
cd "$(dirname "$0")/.."

PROD_DIR="dist/extension-prod"
DEV_DIR="dist/extension-dev"

# Shared source files (everything except env.js and manifest.json, which are generated)
SHARED_FILES=(
  background.js
  content_caliber.js
  content_indeed.js
  content_linkedin.js
  popup.css
  popup.html
  popup.js
)

echo "=== Caliber extension build ==="

# ── Clean ──
rm -rf "$PROD_DIR" "$DEV_DIR"
mkdir -p "$PROD_DIR/icons" "$DEV_DIR/icons"

# ── Copy shared files ──
for f in "${SHARED_FILES[@]}"; do
  cp "extension/$f" "$PROD_DIR/$f"
  cp "extension/$f" "$DEV_DIR/$f"
done

# ── Copy icons ──
cp extension/icons/* "$PROD_DIR/icons/"
cp extension/icons/* "$DEV_DIR/icons/"

# ── Generate env.js — PRODUCTION ──
cat > "$PROD_DIR/env.js" <<'ENVPROD'
// env.js — PRODUCTION (auto-generated by build-extensions.sh)
const CALIBER_ENV = Object.freeze({
  MODE: "production",
  API_BASE: "https://www.caliber-app.com",
  LABEL: "Caliber",
});
ENVPROD

# ── Generate env.js — DEV ──
cat > "$DEV_DIR/env.js" <<'ENVDEV'
// env.js — DEVELOPMENT (auto-generated by build-extensions.sh)
const CALIBER_ENV = Object.freeze({
  MODE: "development",
  API_BASE: "http://localhost:3000",
  LABEL: "Caliber DEV",
});
ENVDEV

# ── Generate manifest.json — PRODUCTION ──
cat > "$PROD_DIR/manifest.json" <<'MPROD'
{
  "manifest_version": 3,
  "name": "Caliber — Job Fit Score",
  "version": "0.4.0",
  "description": "Get a fit score on LinkedIn or Indeed job posts — no copy/paste.",
  "permissions": ["activeTab", "storage", "scripting"],
  "host_permissions": [
    "https://www.caliber-app.com/*",
    "https://www.linkedin.com/*",
    "https://www.indeed.com/*"
  ],
  "background": {
    "service_worker": "background.js"
  },
  "action": {
    "default_popup": "popup.html",
    "default_icon": {
      "16": "icons/icon16.png",
      "48": "icons/icon48.png",
      "128": "icons/icon128.png"
    }
  },
  "content_scripts": [
    {
      "matches": [
        "https://www.caliber-app.com/*"
      ],
      "js": ["env.js", "content_caliber.js"],
      "run_at": "document_idle"
    },
    {
      "matches": [
        "https://www.linkedin.com/jobs/*",
        "https://www.linkedin.com/jobs/view/*"
      ],
      "js": ["env.js", "content_linkedin.js"],
      "run_at": "document_idle"
    },
    {
      "matches": [
        "https://www.indeed.com/*"
      ],
      "js": ["env.js", "content_indeed.js"],
      "run_at": "document_idle"
    }
  ],
  "icons": {
    "16": "icons/icon16.png",
    "48": "icons/icon48.png",
    "128": "icons/icon128.png"
  }
}
MPROD

# ── Generate manifest.json — DEV ──
cat > "$DEV_DIR/manifest.json" <<'MDEV'
{
  "manifest_version": 3,
  "name": "Caliber — Job Fit Score [DEV]",
  "version": "0.4.0",
  "description": "DEV BUILD — localhost only. Get a fit score on LinkedIn or Indeed job posts.",
  "permissions": ["activeTab", "storage", "scripting"],
  "host_permissions": [
    "http://localhost:3000/*",
    "https://www.linkedin.com/*",
    "https://www.indeed.com/*"
  ],
  "background": {
    "service_worker": "background.js"
  },
  "action": {
    "default_popup": "popup.html",
    "default_icon": {
      "16": "icons/icon16.png",
      "48": "icons/icon48.png",
      "128": "icons/icon128.png"
    }
  },
  "content_scripts": [
    {
      "matches": [
        "http://localhost:3000/*"
      ],
      "js": ["env.js", "content_caliber.js"],
      "run_at": "document_idle"
    },
    {
      "matches": [
        "https://www.linkedin.com/jobs/*",
        "https://www.linkedin.com/jobs/view/*"
      ],
      "js": ["env.js", "content_linkedin.js"],
      "run_at": "document_idle"
    },
    {
      "matches": [
        "https://www.indeed.com/*"
      ],
      "js": ["env.js", "content_indeed.js"],
      "run_at": "document_idle"
    }
  ],
  "icons": {
    "16": "icons/icon16.png",
    "48": "icons/icon48.png",
    "128": "icons/icon128.png"
  }
}
MDEV

echo ""
echo "  PROD build -> $PROD_DIR/"
echo "    name:     \"Caliber — Job Fit Score\""
echo "    API_BASE: https://www.caliber-app.com"
echo "    hosts:    caliber-app.com, linkedin.com, indeed.com"
echo ""
echo "  DEV build  -> $DEV_DIR/"
echo "    name:     \"Caliber — Job Fit Score [DEV]\""
echo "    API_BASE: http://localhost:3000"
echo "    hosts:    localhost:3000, linkedin.com, indeed.com"
echo ""
echo "=== Done ==="
