import { generateTitleRecommendation } from "../lib/title_scoring";

const FABIO_RESUME = `Fabio Bellini Keizer, Oregon Professional Summary As an OSOC Security Analyst and dedicated cybersecurity professional, I specialize in penetration testing, vulnerability assessment, and security risk mitigation. I bring a strong focus on protecting organizational assets through the design and implementation of comprehensive security measures. With hands-on experience in tools such as Kali Linux, Active Directory, and Python, I'm proficient in red team operations and network security auditing. My background includes serving as an assistant instructor, mentoring students through practical cybersecurity training programs. I've also completed personal projects including building a custom penetration testing lab with Raspberry Pi and developing Arduino-based hardware solutions that reflect my technical creativity and problem-solving skills. In addition to my technical expertise, I have a diverse professional background, having owned and managed an online retail business and held leadership roles in the hospitality industry. Technical Skills Penetration Testing Cybersecurity Network Security Active Directory Red Team Android Kali Linux HTML Python Language Microsoft 365 Licenses & Certifications CNPen Certified Network Pentester eCPPT Certified Professional Penetration Tester PNPT Practical Network Penetration Tester CompTIA Security+ CE Certification Certified Penetration Tester Education OSCP Bootcamp Evolve Academy Certificate of Completion Active Defense & Cyber Deception SOC Core Skills Red Team Fundamentals for Active Directory API Security Fundamentals Practical Ethical Hacking Professional Experience OSOC Security Analyst May 2024 - present Evolve Security Perform continuous penetration testing to proactively identify and exploit vulnerabilities across networks, web applications, and internal systems. Correlate findings with SOC threat intelligence to prioritize and escalate risks. Automate reconnaissance and exploitation workflows. Provide regular reports and real-time alerts to stakeholders. Assistant Instructor Jan 2024 - present Evolve Academy Guide students toward achieving learning objectives. Implement additional guidance resources and technical exercises. Perform 1-on-1 weekly interviews with students. Assist other assistants and lead instructors with assessments. Owner Jan 2019 - Jan 2022 Athletes Best Equipment Online Clothing Store Tasting Room Lead May 2016 - Nov 2018 Alexana Estate Vineyard & Winery`;

const FABIO_ANSWERS = [
  "The part that felt most like me was investigating problems, connecting technical details, and turning them into something clear and actionable. I enjoy digging into issues, understanding what is really happening, and then communicating that in a way others can use to make decisions.",
  "What drained me fastest was repetitive work that required a lot of manual effort but did not involve much analysis, problem-solving, or improvement. I can do it when needed, but I am at my best when I am solving problems, finding patterns, and helping move work forward in a meaningful way.",
  "People often come to me to help make sense of technical situations, especially when something is unclear, urgent, or needs to be explained well. I am usually the person they ask when they need someone to investigate, organize the details, and turn complexity into a clear next step.",
  "I find complex challenges exciting when they require investigation, critical thinking, and a structured approach. If there is a difficult problem with moving parts, and I can break it down, validate the details, and work toward a practical solution, that energizes me rather than overwhelms me.",
  "I am best at work that sits at the intersection of analysis, problem-solving, and communication. I take complex or messy situations, figure out what matters, and turn that into something useful, whether that is a solution, a recommendation, or a clear path forward.",
];

const JEN_RESUME = `Summary Self-motivated go-getter with over 10 years of experience in sales. Known for exceptional customer service and executing sales strategies that produce results. Natural proclivity to understanding technology and how to sell to clients. Excellent at building alliances and partnerships with customers, prospects and colleagues. Experience Gracer-West Holdings Salem OR Estate Manager 01/2021 Present Maintained and managed a large household and complex of upscale properties for a private client. Role included accounting managing staff coordinating events overseeing new projects and setting up a successful rental property. Responsible for working with owner to execute an overall plan for all properties. Developed acute business skills in computers finance planning and organization. Set a service standard of excellence while on the premises and produced amazing results for client. SOYOUU LLC Keizer OR Owner 01/2013 01/2023 Operated a successful college textbook business for 10 years. Cultivated relationships that were pivotal in understanding how to deliver superior customer service. Achieved over 95% positive customer reviews. Experience with building lucrative products and marketing them to consumers. Skills Customer service Communication skills Computer literacy Leadership Outside Sales Analytical Thinking Knowledge of Main Sales Platforms Advertising Negotiation Active Listening Prospect Communication Identifying Client Needs Product Demonstrations Jennifer Bellini`;

const JEN_ANSWERS = [
  "making marketing materials, design materials. building sops, automations and tools for business. Developing scripts and pitch decks. working directly with customers and understanding their desires and then building solutions around them.",
  "endless sales cycles, jumping from one task to another, not being able to go deep on something, jumping from in home, to cold calls, to pitch decks, to scripts to meetings. I want to feel completed with my work. ship something see how it takes and iterate. sales feels like always chasing the same win",
  "everything i mentioned in prompt 1, and guidance, empathy, listening and good instincts about people and business direction.",
  "discovering bottlenecks and creating strategies to break them. designing beautiful materials for people to look at and engage with. and building tools and automations that make the business run more efficiently.",
  "App building, interior design, songwriting, producing",
];

function print(label: string, result: ReturnType<typeof generateTitleRecommendation>) {
  console.log(`\n=== ${label} ===`);
  console.log(JSON.stringify(result.candidates, null, 2));
  console.log(JSON.stringify(result.recommendation.titles, null, 2));
}

print("FABIO", generateTitleRecommendation(FABIO_RESUME, FABIO_ANSWERS));
print("JEN", generateTitleRecommendation(JEN_RESUME, JEN_ANSWERS));
